# ansible-playbook -i ./lifecycle_inventory.py ./retire_host.yml
# -e@/vars/env.yml --limit Terminating_Wait

#
# This is separate because it's use of handlers
# leads to various race conditions.
#
- name: Stop all services
  hosts: Terminating_Wait
  sudo: True
  gather_facts: False
  vars:
    STOP_ALL_EDX_SERVICES_EXTRA_ARGS: "--no-wait"
  roles:
    - stop_all_edx_services

- name: Server retirement workflow
  hosts: Terminating_Wait
  sudo: True
  gather_facts: False
  tasks:
    # We only force a rotation of edx logs.
    # Forced rotation of system logfiles will only
    # work if there hasn't already been a previous rotation
    - name: Force a log rotation which will call the log sync
      command: /usr/sbin/logrotate -f /etc/logrotate.d/hourly/{{ item }}
      with_items:
        - "tracking.log"
        - "edx-services"

- name: Run minos verification
  hosts: Terminating_Wait
  sudo: True
  gather_facts: False
  tasks:
    - name: Run minos
      command: /edx/app/minos/venvs/bin/minos --config /edx/etc/minos/minos.yml --json
